### ISSUE TITLE
Use Butterknife for the bindings

### ISSUE THREAD

**Issue by Jnsll** [eloisance/fete-de-la-science#1]
Using annotations instead of writing 'findById' several times.

Website : https://jakewharton.github.io/butterknife/
GitHub: https://github.com/JakeWharton/butterknife
Tutorial : http://www.vogella.com/tutorials/AndroidButterknife/article.html

**Comment by eloisance** [comment]
Another good tutorial --> https://www.androidhive.info/2017/10/android-working-with-butterknife-viewbinding-library/

**Comment by Kwodhan** [comment]
In build.gradle :
compile 'com.jakewharton:butterknife:8.5.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
